// The learning path. Order matters: it is the suggested reading order and is
// used to compute "what should I do next". Each topic maps to the section of
// TAOCP Volume 1 (3rd ed.) where Knuth introduces the material, plus the
// chapter of Concrete Mathematics (Graham, Knuth, Patashnik) that goes deeper.

export const topics = [
  {
    id: 'induction',
    title: 'Mathematical Induction',
    short: 'Induction',
    taocp: '§1.2.1',
    concrete: 'Ch. 1 (Recurrent Problems)',
    blurb: 'The proof technique behind almost every algorithm correctness argument in the book.',
    prereqs: [],
    explorer: null,
  },
  {
    id: 'numbers',
    title: 'Numbers, Powers, and Logarithms',
    short: 'Powers & logs',
    taocp: '§1.2.2',
    concrete: 'Ch. 3 & 9',
    blurb: 'Exponent and logarithm rules, the meaning of lg, ln, log, and why bits ≈ log₂.',
    prereqs: [],
    explorer: null,
  },
  {
    id: 'sums',
    title: 'Sums and Products',
    short: 'Sums',
    taocp: '§1.2.3',
    concrete: 'Ch. 2 (Sums)',
    blurb: 'Sigma notation as a tool: shifting indices, swapping the order of summation, telescoping.',
    prereqs: ['induction'],
    explorer: null,
  },
  {
    id: 'intfuncs',
    title: 'Integer Functions and Elementary Number Theory',
    short: 'Floors, mods, gcd',
    taocp: '§1.2.4',
    concrete: 'Ch. 3 & 4',
    blurb: 'Floor, ceiling, Knuth’s mod, Euclid’s algorithm, and congruences.',
    prereqs: ['numbers'],
    explorer: 'euclid',
  },
  {
    id: 'permutations',
    title: 'Permutations and Factorials',
    short: 'Factorials',
    taocp: '§1.2.5',
    concrete: 'Ch. 5 & 9',
    blurb: 'Counting arrangements, n!, its prime factorisation, and Stirling’s approximation.',
    prereqs: ['sums'],
    explorer: null,
  },
  {
    id: 'binomial',
    title: 'Binomial Coefficients',
    short: 'Binomials',
    taocp: '§1.2.6',
    concrete: 'Ch. 5 (Binomial Coefficients)',
    blurb: 'Pascal’s triangle and the handful of identities Knuth uses constantly.',
    prereqs: ['permutations', 'sums'],
    explorer: 'pascal',
  },
  {
    id: 'harmonic',
    title: 'Harmonic Numbers',
    short: 'Harmonic numbers',
    taocp: '§1.2.7',
    concrete: 'Ch. 6.3 & 9',
    blurb: 'H_n = 1 + 1/2 + ⋯ + 1/n, its logarithmic growth, and where it appears in algorithm analysis.',
    prereqs: ['sums', 'numbers'],
    explorer: 'harmonic',
  },
  {
    id: 'fibonacci',
    title: 'Fibonacci Numbers',
    short: 'Fibonacci',
    taocp: '§1.2.8',
    concrete: 'Ch. 6.6',
    blurb: 'The recurrence, the golden ratio, Binet’s formula, and the identities Knuth uses.',
    prereqs: ['induction'],
    explorer: 'fibonacci',
  },
  {
    id: 'genfuncs',
    title: 'Generating Functions',
    short: 'Generating functions',
    taocp: '§1.2.9',
    concrete: 'Ch. 7',
    blurb: 'Power series as bookkeeping devices for sequences; solving recurrences mechanically.',
    prereqs: ['binomial', 'fibonacci'],
    explorer: 'genfunc',
  },
  {
    id: 'recurrences',
    title: 'Recurrence Relations',
    short: 'Recurrences',
    taocp: '§1.2.9, §1.2.10',
    concrete: 'Ch. 1 & 7',
    blurb: 'Solving the recurrences that fall out of analysing an algorithm.',
    prereqs: ['induction', 'genfuncs'],
    explorer: null,
  },
  {
    id: 'asymptotics',
    title: 'Asymptotics and O-Notation',
    short: 'O-notation',
    taocp: '§1.2.11',
    concrete: 'Ch. 9 (Asymptotics)',
    blurb: 'O, Ω, Θ, growth rates, and Knuth’s one-way equalities.',
    prereqs: ['numbers', 'harmonic'],
    explorer: 'growth',
  },
  {
    id: 'analysis',
    title: 'Analysis of an Algorithm',
    short: 'Algorithm analysis',
    taocp: '§1.2.10',
    concrete: 'Ch. 8 (Discrete Probability)',
    blurb: 'Expected values, variance, and the probabilistic analysis of Knuth’s Algorithm M.',
    prereqs: ['harmonic', 'sums', 'genfuncs'],
    explorer: null,
  },
];

export const topicById = Object.fromEntries(topics.map((t) => [t.id, t]));

export const explorers = [
  { id: 'pascal', title: 'Pascal’s Triangle', blurb: 'Colour binomial coefficients by parity or modulo p, and trace the classic identities.', topic: 'binomial' },
  { id: 'euclid', title: 'Euclid’s Algorithm', blurb: 'Step through gcd(m, n) and the extended algorithm that finds m·a + n·b = gcd.', topic: 'intfuncs' },
  { id: 'harmonic', title: 'Harmonic Numbers vs. ln n', blurb: 'Watch H_n hug ln n + γ as n grows.', topic: 'harmonic' },
  { id: 'fibonacci', title: 'Fibonacci and the Golden Ratio', blurb: 'Binet’s formula in action, and how fast the ratio converges to φ.', topic: 'fibonacci' },
  { id: 'genfunc', title: 'Generating Function Expander', blurb: 'Type a rational generating function and read off its coefficients.', topic: 'genfuncs' },
  { id: 'growth', title: 'Growth-Rate Race', blurb: 'Compare log n, √n, n, n log n, n², 2ⁿ and n! on a log-scale plot.', topic: 'asymptotics' },
];

export const explorerById = Object.fromEntries(explorers.map((e) => [e.id, e]));
